### ISSUE TITLE
Desarrollo de Sección "Testimonios"

### ISSUE THREAD

**Issue by imsamudev** [imsamudev/DreamTravels#13]
### Procedemos al desarrollo de la sección de Reservas, requerimientos:

- Desarrollarse en mobile first.
- La sección debe ser responsive.
- Implementar un slider manual para que los usuarios puedan desplazar o hacer clic para ver más testimonios.
- La sección debe incluir un aproximado de 10 comentarios en total.
- Asegurarse de que el diseño sea limpio y que el texto sea fácilmente legible.
- Implementar animaciones suaves para el deslizamiento de los testimonios cuando el usuario interactúe con el slider.

### Criterios de aceptación:

- La sección de testimonios es completamente responsive.
- El slider manual funciona sin errores y permite a los usuarios desplazarse por los testimonios tanto en móviles como en pantallas grandes.
- La sección incluye como mínimo 7 comentarios.
- Los testimonios son legibles y se muestran correctamente en todas las pantallas.

**Comment by ezomoza** [comment]
error de subida en los dos últimos commits, en realidad pertenecen al issue #12 sección de reservas
